Add support for the `time` crate
instructure/paseto pull request #32
Opened 2020-11-13 23:06 UTC by Weasy666

This commit puts `chrono` behind a feature flag and adds `time` as an alternative to it.

One thing to note is, that i had to exclude https://github.com/Weasy666/paseto/blob/1b97dcb99565807e43057e96470a03472ed9ac46/src/tokens/mod.rs#L51 from being build, when both features `easy_token_chrono` and `easy_token_time` are activated, as there is no way to guess which time crate should be used to parse the json time.

2020-11-13 23:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/paseto?pullRequest=32) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/paseto?pullRequest=32) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/paseto?pullRequest=32) it.</sub>

2020-11-13 23:42 UTC, Mythra requested changes
This seems like great work so far! Thanks so much for putting in the work!

2020-11-13 23:42 UTC, Mythra commented on README.md
> +[![Crates.io](https://img.shields.io/crates/v/paseto.svg)](https://crates.io/crates/paseto)
Let's remove these for now, we can add them in a new PR, but should keep PRs focused on one thing at a time :)

2020-11-13 23:42 UTC, Mythra commented on examples/local-using-builders.rs
> +  #[cfg(feature = "easy_tokens_chrono")]
Can we add to this example to have a time example as well? 😄

2020-11-13 23:42 UTC, Mythra commented on examples/public-using-builder.rs
> +  #[cfg(all(feature = "v2", feature = "easy_tokens_chrono"))]
Another example for time here would be great!

2020-11-13 23:42 UTC, Mythra commented on src/tokens/builder.rs
> +#[cfg(all(feature = "easy_tokens_chrono", not(feature = "easy_tokens_time")))]
I don't think these includes should be `all(not())` , do these work if I specify both chrono and time? I believe these should just be: `#[cfg(feature = "easy_tokens_chrono")]` since they don't conflict like the functions below.

2020-11-13 23:42 UTC, Mythra commented on src/tokens/mod.rs
> +#[cfg(all(feature = "easy_tokens_chrono", not(feature = "easy_tokens_time")))]
See note about cfg features above

2020-11-13 23:42 UTC, Mythra commented on src/tokens/mod.rs
> +#[cfg(any(not(feature = "easy_tokens_time"), not(feature = "easy_tokens_chrono")))]
Since this is arguably one of the most useful features of easy_token could we perhaps add a function similar to how we have above that accepts an enum value of whether or not to validate with chrono/time?

2020-11-15 11:11 UTC, Weasy666 commented on src/tokens/builder.rs
> +#[cfg(all(feature = "easy_tokens_chrono", not(feature = "easy_tokens_time")))]
🤦‍♂️ Yeah absolutely! I guess, i was to deep in copy&paste mode 😅

2020-11-15 12:33 UTC, Weasy666 commented on src/tokens/mod.rs
> +#[cfg(any(not(feature = "easy_tokens_time"), not(feature = "easy_tokens_chrono")))]
The function still works when only one time feature is activated. Yeah sure. I initially wanted to do something like this
```rust
pub fn validate_potential_json_blob<T: FromStr>(data: &str) -> Result<JsonValue, Error>
```
but unfortunately, `time` does not implemented that trait. Just so that i understood you correctly, i should change the function to something like this, right?
```
pub enum TargetTime<'a> {
    Chrono(&'a str),
    Time(&'a str),
}

pub fn validate_potential_json_blob(data: &TargetTime)
```

Aaand...do you maybe have a suggestion for the name of the new enum? I am bad at naming things 😅

2020-11-17 15:58 UTC, Mythra commented on src/tokens/mod.rs
> +#[cfg(any(not(feature = "easy_tokens_time"), not(feature = "easy_tokens_chrono")))]
Oh sorry missed this! How about: `TimeBackend`?

2020-11-18 06:17 UTC, Mythra reviewed
Looking great so far! Thanks for all your work!

2020-11-18 06:17 UTC, Mythra commented on examples/local-using-builders.rs
> +use serde_json::json;
This serde_json line also needs a cfg feature. Since it's only included if one of time/chrono is included.

2020-11-18 06:17 UTC, Mythra commented on examples/public-using-builder.rs
>    serde_json::json,
Same with this serde_json

2020-11-18 06:17 UTC, Mythra commented on src/tokens/mod.rs
> +  #[cfg(feature = "easy_tokens_chrono")]
Can we just add a quick comment blurb on what this enum does since it's a public enum? :)

2020-11-19 21:26 UTC, Weasy666 commented
Ok...this should again be ready for a review. Hopefully the final one 😅🙃. Sorry for missing all the little things.

2020-11-19 22:12 UTC, Mythra approved these changes
No need to be sorry at all, thanks for your hard work! We'll merge this in for now, and I'll work on doing some things on my end and cutting a release!

2020-11-19 22:12 UTC, merged

2020-11-20 07:42 UTC, Weasy666 commented
You are welcome. And happy to hear that.

2020-12-08 23:00 UTC, frederikbosch commented
Good work on this PR! I am happy use of the lib and hope a new version can be released. Would that be an option?

2020-12-08 23:34 UTC, Mythra commented
Hey @frederikbosch ,

Yep I'm getting to it, unfortunately have had some other things pop up first. But I'll schedule for some time for it, at the latest I'd expect this weekend.