fix expired bug, improve errors
instructure/paseto pull request #34
Opened 2020-12-09 12:51 UTC by frederikbosch

While I was debugging #33 to fix the bug that an valid expiration date was rejected by `validate_local_token`, I decided that more clear errors help to debug why something is failing. This PR fixes one thing: the wrong comparison character was used `>` vs `<` and more errors are added to improve library usage experience.

2020-12-09 16:17 UTC, Mythra requested changes
Hey thanks so much for your PR, and catching that nasty bug!

I admit when first creating this crate I air'd on the side of not giving any information away, and made the errors particularly vague. I didn't want an attacker to be able to use that information, and do something with it. Thinking back on it now though they were definitely _way too vague_, and this info you provided is certainly useful (as you found out yourself!)

I'm all for this PR, I have the one comment about adding the claim name to unparseable date that I'd like to see, the other comment is technically optional, but curious what you think.

2020-12-09 16:17 UTC, Mythra commented on src/errors.rs
> +  UnparseableTokenDate {},
Let's go ahead and add _which_ claim has the unparseable date here:

```rust
#[fail(display = "The claim: {}, has an invalid date", claim_name)]
UnparseableTokenDate { claim_name: &'static str },
```

2020-12-09 16:17 UTC, Mythra commented on src/errors.rs
> +  #[fail(display = "This token contains an issued at date that is not in the past (IAT claim).")]
This phrase parses a bit weirdly for me. Perhaps a better way of wording is: "This token has not yet been issued, the issued at claim (IAT) is in the future", WDYT?

2020-12-10 09:17 UTC, frederikbosch commented
Nice suggestions, will take them both into account.

2020-12-11 15:07 UTC, frederikbosch commented
Done!

2020-12-11 17:38 UTC, Mythra commented on src/tokens/mod.rs
> +        .ok_or(GenericError::UnparseableTokenDate {})
looks like some of these are missing field names! just a quick cleanup, you can see these when running: `cargo test --features "v1,v2,easy_tokens_time"`

2020-12-17 14:45 UTC, frederikbosch commented
I resolved those last week. There are some more other issues outstanding when running `cargo test --features "v1,v2,easy_tokens_time"`. I did not find the time (yet) to fix those. Could you perhaps take a look?

2021-01-11 21:52 UTC, Mythra commented
Ah looks like github didn't get the memo this was merged. Sorry about the delay, holidays and all. Also sorry about the failures! Turns out there were some edge cases when chrono + time were being used in conjuction that weren't caught cause we didn't think anyone would use that!

(Both were being included because chrono is default and without --no-default-features it included both).

Anyway it's been fixed, and this PR is merged! 

Thank you so much for your contribution!

2021-01-11 21:52 UTC, closed without merging

2021-01-12 09:45 UTC, frederikbosch commented
Thank you, for merging and the wonderful library!