Proposed additions to the builder implementation to make adding claims more flexible...
instructure/paseto pull request #45
Opened 2021-09-15 00:47 UTC by rrrodzilla

Thanks for submitting a PR! We want to make contributing to Paseto as easy as possible.
Please read these instructions carefully:

- [ ] Explain the **motivation** for making this change.
- [ ] Provide a **test plan** demonstrating that the code is solid.
- [ ] Match the **code formatting** of the rest of the codebase.
- [ ] Make sure to **add tests** to help keep code coverage up.

## Motivation (required) ##

What existing problem does the pull request solve?
Hi, thanks for this great Paseto implementation.  One issue which frustrated me when using the builder is that I need to add additional claims one at a time using the `set_claim` method.  This requires each individual specific claim to be known when using the builder to assemble a token.  In order to make my code as reusable as possible, and potentially buried within a crate or bin of its own, I need to be able to dynamically inject an arbitrary list of claims I want to include from elsewhere.  To do so, I've added two new methods to use either in place of or in conjunction with the `set_claim` method.  The first simply pluralizes the method and is called `set_claims` and receives as an input a HashMap of Values to extend the existing internal `extra_claims` attribute of the builder.  the `std::iter::Extend` trait is used to merge the values into the existing HashMap.  The second method is named `set_claims_by_closure` and does the same as the `set_claims` method however instead of receiving a HashMap as an input to extend, it receives a closure which returns a HashMap and is then used to extend the internal HashMap.

## Test Plan (required) ##
I"ve added a test for each method:
1can_construct_a_token_chrono_with_claims_closure()`
1can_construct_a_token_chrono_with_claims_hashmap()`
For each, I've essentially just copied the `can_construct_a_token_chrono()` test and updated how the claims are created and set, and then verified they existed after the token was decrypted.

All tests currently pass.

Thanks for your consideration.

2021-09-15 00:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/paseto?pullRequest=45) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/paseto?pullRequest=45) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/paseto?pullRequest=45) it.</sub>

2021-09-15 23:08 UTC, Mythra requested changes
Thanks so much! I'm on board with having a way to set multiple claims at once. Certainly a great thing to be able to do. Thanks so much for your contribution, just a few more changes and I think we can get this shipped! 🎉

2021-09-15 23:08 UTC, Mythra commented on src/tokens/builder.rs
> +  pub fn set_claims(&'a mut self, claims: HashMap<&'a str, Value>) -> &'a mut Self {
Can we change this to be `extend_claims` to be more inline with the standard methods?:

```suggestion
  pub fn extend_claims(&'a mut self, claims: HashMap<&'a str, Value>) -> &'a mut Self {
```

2021-09-15 23:08 UTC, Mythra commented on src/tokens/builder.rs
> +  /// https://doc.rust-lang.org/std/iter/trait.Extend.html
FWIW these links at the end aren't proper rustdoc links (they won't be linkified) since they're not enclosed in `<>` (since rustdoc is just markdown).

However, there's actually an even better thing we can do here which is just use: [`std::iter::Extend`], see: <https://doc.rust-lang.org/rustdoc/linking-to-items-by-name.html>.

As such a better way to write this may be:

```suggestion
  /// Provide multiple arbitrary claims at once, if a key is already present it will be updated.
  ///
  /// Mirrors [`std::iter::Extend`] for normal maps.
```

2021-09-15 23:08 UTC, Mythra commented on src/tokens/builder.rs
> +  pub fn set_claims_by_closure<F>(&'a mut self, claims_closure: F) -> &'a mut Self
I'm not quite sure I understand the utility of this method. Can you show a concrete example of what you're trying to do?

2021-09-16 02:29 UTC, rrrodzilla commented on src/tokens/builder.rs
> +  pub fn set_claims(&'a mut self, claims: HashMap<&'a str, Value>) -> &'a mut Self {
Done.  Great suggestion.  I love that.

2021-09-16 02:29 UTC, rrrodzilla commented on src/tokens/builder.rs
> +  /// https://doc.rust-lang.org/std/iter/trait.Extend.html
Thanks for that.  I had no clue!

2021-09-16 02:32 UTC, rrrodzilla commented on src/tokens/builder.rs
> +  pub fn set_claims_by_closure<F>(&'a mut self, claims_closure: F) -> &'a mut Self
Thanks for talking me down from my random coding spree.  After you pointed it out, I realized I could do exactly what I need to do outside of this crate and just using the new `extend_claims` method.  I removed this one as well as its test. Thanks again!

2021-09-16 03:48 UTC, Mythra approved these changes
Aweseome thanks for the changes! I'll go ahead and merge this in, thank you so much for your contribution. 

This probably won't go out in an official release until we also add in support for v3/v4 but you can use a git target in Cargo.toml til then if it's needed.

2021-09-16 03:48 UTC, merged